library(graphite)
library(biomaRt)
library(RCurl)
library(stringr)
library(jsonlite)
library(httr)

#import filename
args=(commandArgs(TRUE))
if(length(args)==0){
  print("No arguments supplied.")
}
images <- TRUE #retrieve images from Reactome

#setwd("~/Desktop")
infile <- args[1]
#infile <- "CRC_edgeR.txt_entrez.tsv_2022-10-08_08-23-30_SPIA_Results.csv"
#infile <- "enrichr_results1.csv" #enrichr data
outfile <- paste0(infile,"-Treatments.tsv")
outfile1 <- paste0(infile,"-RankedTargets.tsv")
setwd("~/fsl_groups/fslg_PickettLabGroup/spia")
#setwd("~/")
merged_drugs <- as.data.frame(NULL)
trac_vector <- as.vector(c(1,2,3,9,10,11,18,19,20,26,27,28))

#define weights
vlow <- 0.01
low <- 0.5
med <- 1
hi <- 2
p3_w <- 1.5
p2_w <- 1
p1_w <- .5
p4_w <- 2

#df_init <- data.frame(matrix(ncol = 11, nrow = 0))
#colnames(df_init) <- c("Target_ID","Target_Symbol","Target_Name","Drug_ID","Drug_Name","Is_FDA_Approved","Highest_Clinical_Trial_Phase","Has_Been_Withdrawn","Approved_Indications","Pathway_DB","Pathway_Name")

#import relevant pathways
humanReactome <- pathways("hsapiens", "reactome")
humanKEGG <- pathways("hsapiens", "kegg")
humanBioCarta <- pathways("hsapiens", "biocarta")
humanNCI <- pathways("hsapiens", "nci")
humanPanther <- pathways("hsapiens", "panther")

#read in spia results table
#setwd("~/Downloads")
in_data <- read.csv(file = infile, header = TRUE, sep = ",")
enrichr <- FALSE

#modify input table if it was generated by enrichr
if(ncol(in_data)==9){#data is csv from enrichr analysis
  #filter non-significant pathways
  in_data <- subset(in_data,Adjusted.P.value < 0.05)
  #add Reactome column
  new_path_col <- as.vector(rep("Reactome",nrow(in_data)))
  in_data <- cbind(in_data,new_path_col)
  #manipulate data frame
  in_data$Old.P.value <- NULL
  in_data$Old.Adjusted.P.value <- NULL
  Split <- strsplit(as.character(in_data$Overlap), "/", fixed = TRUE)
  NDE <- sapply(Split, "[", 1)
  pSize <- sapply(Split, "[", 2)
  in_data <- cbind(in_data,NDE)
  in_data <- cbind(in_data,pSize)
  in_data$Overlap <- NULL
  #change colnames for significance and pathway name
  vec_enrichr_names <- as.vector(c("Name","pG","pGFWER","Odds.Ratio","Combined.Score","Genes","SourceDB","NDE","pSize"))
  colnames(in_data) <- vec_enrichr_names
  Split1 <- strsplit(as.character(in_data$Name), " R-HSA-", fixed = TRUE)
  Reactome_path_name <- as.vector(sapply(Split1, "[", 1))
  #Reactome_path_ID <- sapply(Split, "[", 2)
  in_data$Name <- Reactome_path_name
  enrichr <- TRUE
  rm(Split1, Split, NDE, pSize)
}

sig_paths <- as.vector(in_data$Name)
sig_dbs <- as.vector(in_data$SourceDB)

for(i in 1:length(sig_dbs)){
  #i <- 1
  print(paste0("Working...Pathway ",i," of ", length(sig_dbs)," : ",sig_paths[i]))
  
  if(sig_dbs[i] == "KEGG"){
    if(length(humanKEGG@entries[[sig_paths[i]]])==0){
     print(paste0("Skipping...Pathway ",i," of ", length(sig_dbs)," : ",sig_paths[i]," -- No Protein Data"))
     next()
    }
    db_entrezID <- as.vector(humanKEGG@entries[[sig_paths[i]]]@protEdges[["src"]])
    db_entrezID <- c(db_entrezID,humanKEGG@entries[[sig_paths[i]]]@protEdges[["dest"]])
    db_entrezID <- db_entrezID[!duplicated(db_entrezID)]
    
    mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
    genes <- getBM(
      filters="entrezgene_id",
      attributes=c("ensembl_gene_id", "entrezgene_id"),#, "hgnc_symbol", "uniprot_gn_id"),#, "go_id", "name_1006"),
      values=db_entrezID,
      mart=mart,
      unique = TRUE)
  }else if(sig_dbs[i] == "Reactome"){
    #print("in Reactome loop")
    if(length(humanReactome@entries[[sig_paths[i]]])==0){
      print(paste0("Skipping...Pathway ",i," of ", length(sig_dbs)," : ",sig_paths[i]," -- No Protein Data"))
      next()
    }
    db_entrezID <- as.vector(humanReactome@entries[[sig_paths[i]]]@protEdges[["src"]])
    db_entrezID <- c(db_entrezID,humanReactome@entries[[sig_paths[i]]]@protEdges[["dest"]])
    db_entrezID <- db_entrezID[!duplicated(db_entrezID)]
    
    mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
    genes <- getBM(
      filters="uniprotswissprot",
      attributes=c("uniprotswissprot", "ensembl_gene_id", "entrezgene_id"),#, "hgnc_symbol", "uniprot_gn_id"),#, "go_id", "name_1006"),
      values=db_entrezID,
      mart=mart,
      unique = TRUE)
  }else if(sig_dbs[i] == "NCI"){
    if(length(humanNCI@entries[[sig_paths[i]]])==0){
      print(paste0("Skipping...Pathway ",i," of ", length(sig_dbs)," : ",sig_paths[i]," -- No Protein Data"))
      next()
    }
    db_entrezID <- as.vector(humanNCI@entries[[sig_paths[i]]]@protEdges[["src"]])
    db_entrezID <- c(db_entrezID,humanNCI@entries[[sig_paths[i]]]@protEdges[["dest"]])
    db_entrezID <- db_entrezID[!duplicated(db_entrezID)]
    
    mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
    genes <- getBM(
      filters="uniprotswissprot",
      attributes=c("uniprotswissprot", "ensembl_gene_id", "entrezgene_id"),#, "hgnc_symbol", "uniprot_gn_id"),#, "go_id", "name_1006"),
      values=db_entrezID,
      mart=mart,
      unique = TRUE)
  }else if(sig_dbs[i] == "Panther"){
    if(length(humanPanther@entries[[sig_paths[i]]])==0){
      print(paste0("Skipping...Pathway ",i," of ", length(sig_dbs)," : ",sig_paths[i]," -- No Protein Data"))
      next()
    }
    db_entrezID <- as.vector(humanPanther@entries[[sig_paths[i]]]@protEdges[["src"]])
    db_entrezID <- c(db_entrezID,humanPanther@entries[[sig_paths[i]]]@protEdges[["dest"]])
    db_entrezID <- db_entrezID[!duplicated(db_entrezID)]
    
    mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
    genes <- getBM(
      filters="uniprotswissprot",
      attributes=c("uniprotswissprot", "ensembl_gene_id", "entrezgene_id"),#, "hgnc_symbol", "uniprot_gn_id"),#, "go_id", "name_1006"),
      values=db_entrezID,
      mart=mart,
      unique = TRUE)
  }else if(sig_dbs[i] == "Biocarta"){
    if(length(humanBioCarta@entries[[sig_paths[i]]])==0){
      print(paste0("Skipping...Pathway ",i," of ", length(sig_dbs)," : ",sig_paths[i]," -- No Protein Data"))
      next()
    }
    db_entrezID <- as.vector(humanBioCarta@entries[[sig_paths[i]]]@protEdges[["src"]])
    db_entrezID <- c(db_entrezID,humanBioCarta@entries[[sig_paths[i]]]@protEdges[["dest"]])
    db_entrezID <- db_entrezID[!duplicated(db_entrezID)]
  }else{
    print(paste0("Error: no valid pathway: ",sig_dbs[i]))
    next()
  }
#  entrez.genes <- db_entrezID
#  mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
#  genes <- getBM(
#    filters="entrezgene_id",
#    attributes=c("ensembl_gene_id", "entrezgene_id"),#, "hgnc_symbol", "uniprot_gn_id"),#, "go_id", "name_1006"),
#    values=db_entrezID,
#    mart=mart,
#    unique = TRUE)
  
  #remove duplicate entrezIDs
  genes <- genes[!duplicated(genes$entrezgene_id), ]
  ensembl_vector <- as.vector(genes$ensembl_gene_id)
  
  #build query string:
  #**note, does not use "tradeNames" or "approvedIndications" as data under "drug" table
  query_string = "
       query target($ensemblId: String!){
    target(ensemblId: $ensemblId){
      id
      approvedSymbol
      approvedName
      associatedDiseases {
        count
      }
      tractability {
        modality
        id
        value
      }
      safetyLiabilities {
        event
      }
      subcellularLocations{
        location
      }
    knownDrugs {
      uniqueDrugs
      rows {
        drug {
          id
          name
          isApproved
          maximumClinicalTrialPhase
          hasBeenWithdrawn
        }
      }
    }
   }
  }
  "
  # Set base URL of GraphQL API endpoint
  base_url <- "https://api.platform.opentargets.org/api/v4/graphql"
  
  #submit to openTargets.org
  for(k in 1:length(ensembl_vector)){
    #k <- 2
    target <- ensembl_vector[k]
    #target <- "ENSG00000232810"
    #target <- "ENSG00000197919"
    #target <- "ENSG00000185436"
    # Set variables object of arguments to be passed to endpoint
    variables <- list("ensemblId" = target)
    # Construct POST request body object with query string and variables
    post_body <- list(query = query_string, variables = variables)
    # Perform POST request
    r <- POST(url=base_url, body=post_body, encode='json')
    # print to console
    #print(content(r)$data)
    target_data <- content(r)$data
    
    #if(length(target_data[["data"]][["drug"]] > 0)){
    if(length(unlist(target_data[["target"]][["knownDrugs"]])) == 0){
      print(paste0("Pathway Member ",k," of ",length(ensembl_vector)," No drugs found: ",ensembl_vector[k]))
    }else{
      print(paste0("Pathway Member ",k," of ",length(ensembl_vector)," Drug(s) found:  ", ensembl_vector[k]))
      
      for(y in 1:length(target_data[["target"]][["knownDrugs"]][["rows"]])){
        #y <- 1
        tractability <- 0
        unique_chembl <- as.vector(NULL)
        inter_col <- as.vector(unlist(target_data[["target"]][["knownDrugs"]][["rows"]][[y]][["drug"]]))
        inter_col <- as.character(inter_col)
        #sum tractability at "approved", "advanced clinical trials", or "phase 1 trials" for SM, Ab, PR, and OC
        for(z in 1:length(trac_vector)){
          #z <- 1
          if(length(target_data[["target"]][["tractability"]])==0){
            sm_approved <- "Unknown"
            sm_advancedClinical <- "Unknown"
            sm_phase1 <- "Unknown"
            ab_approved <- "Unknown"
            ab_advancedClinical <- "Unknown"
            ab_phase1 <- "Unknown"
            pr_approved <- "Unknown"
            pr_advancedClinical <- "Unknown"
            pr_phase1 <- "Unknown"
            oc_approved <- "Unknown"
            oc_advancedClinical <- "Unknown"
            oc_phase1 <- "Unknown"
          }else if(length(target_data[["target"]][["tractability"]])>0){
            sm_approved <- target_data[["target"]][["tractability"]][[1]][["value"]]
            sm_advancedClinical <- target_data[["target"]][["tractability"]][[2]][["value"]]
            sm_phase1 <- target_data[["target"]][["tractability"]][[3]][["value"]]
            ab_approved <- target_data[["target"]][["tractability"]][[8]][["value"]]
            ab_advancedClinical <- target_data[["target"]][["tractability"]][[9]][["value"]]
            ab_phase1 <- target_data[["target"]][["tractability"]][[10]][["value"]]
            pr_approved <- target_data[["target"]][["tractability"]][[18]][["value"]]
            pr_advancedClinical <- target_data[["target"]][["tractability"]][[19]][["value"]]
            pr_phase1 <- target_data[["target"]][["tractability"]][[20]][["value"]]
            oc_approved <- target_data[["target"]][["tractability"]][[26]][["value"]]
            oc_advancedClinical <- target_data[["target"]][["tractability"]][[27]][["value"]]
            oc_phase1 <- target_data[["target"]][["tractability"]][[28]][["value"]]
              if(target_data[["target"]][["tractability"]][[z]][["value"]]=="TRUE"){
                tractability <- tractability+1
              }
          }
        }
        if(length(target_data[["target"]][["subcellularLocations"]])==0){
          subCellLoc <- "No data"
        }else if(length(target_data[["target"]][["subcellularLocations"]])>0){
          subCellLoc <- as.vector(unlist(target_data[["target"]][["subcellularLocations"]][[1]]))
        }
        #make sure to only store unique records 
        if(length(unique_chembl) == 0){
          unique_chembl <- inter_col[1]
          # #if drug has no approved indications, then add an N/A for the record
          # if(length(inter_col == 5)){
          #   inter_col[6] <- as.character("N/A")
          # }
          temp_row <- as.vector(c(target_data[["target"]][["id"]],target_data[["target"]][["approvedSymbol"]],target_data[["target"]][["approvedName"]],target_data[["target"]][["associatedDiseases"]][["count"]],tractability,sm_approved,sm_advancedClinical,sm_phase1,ab_approved,ab_advancedClinical,ab_phase1,pr_approved,pr_advancedClinical,pr_phase1,oc_approved,oc_advancedClinical,oc_phase1,subCellLoc,length(target_data[["target"]][["safetyLiabilities"]]),target_data[["target"]][["knownDrugs"]][["uniqueDrugs"]],inter_col,sig_dbs[i], sig_paths[i]))
          temp_row <- as.data.frame(t(temp_row))
          #if(is.numeric(temp_row[22])==FALSE){
          #  next()
          #}
          merged_drugs <- as.data.frame(rbind(merged_drugs,temp_row),stringsAsFactors = FALSE, drop = FALSE)
          #write.table(df_init, file = outfile, row.names = FALSE, col.names=TRUE, sep = "\t", append = FALSE)
          
        }else if(grep(inter_col[1],unique_chembl) > 0){
          print(paste0("Duplicate drug found for same target: ",inter_col[1]))
          next()
        }else if(grep(inter_col[1],unique_chembl) == 0){
          unique_chembl <- c(unique_chembl, inter_col[1])
          #if drug has no approved indications, then add an N/A for the record
          if(length(inter_col == 5)){
            inter_col[6] <- as.character("N/A")
          }
          temp_row <- as.vector(c(target_data[["target"]][["id"]],target_data[["target"]][["approvedSymbol"]],target_data[["target"]][["approvedName"]],target_data[["target"]][["associatedDiseases"]][["count"]],tractability,target_data[["target"]][["tractability"]][[1]][["value"]],target_data[["target"]][["tractability"]][[2]][["value"]],target_data[["target"]][["tractability"]][[3]][["value"]],target_data[["target"]][["tractability"]][[9]][["value"]],target_data[["target"]][["tractability"]][[10]][["value"]],target_data[["target"]][["tractability"]][[11]][["value"]],target_data[["target"]][["tractability"]][[18]][["value"]],target_data[["target"]][["tractability"]][[19]][["value"]],target_data[["target"]][["tractability"]][[20]][["value"]],target_data[["target"]][["tractability"]][[26]][["value"]],target_data[["target"]][["tractability"]][[27]][["value"]],target_data[["target"]][["tractability"]][[28]][["value"]],subCellLoc,length(target_data[["target"]][["safetyLiabilities"]]),target_data[["target"]][["knownDrugs"]][["uniqueDrugs"]],inter_col,sig_dbs[i], sig_paths[i]))
          temp_row <- as.data.frame(t(temp_row))
          merged_drugs <- as.data.frame(rbind(merged_drugs,temp_row),stringsAsFactors = FALSE)
        }
        
        rm(inter_col)
        rm(temp_row)
      }
      
      #$temp_df <- as.data.frame(do.call("cbind",list(target_data[["target"]][["id"]], target_data[["target"]][["approvedSymbol"]], target_data[["target"]][["approvedName"]], unlist(target_data[["target"]][["knownDrugs"]][["rows"]][[1]]),sig_dbs[i], sig_paths[i])))
      
      #drug_merged <- as.data.frame(do.call("cbind", list(target_data[["data"]][["target"]][["gene_info"]][["symbol"]],target_data[["data"]][["target"]][["gene_info"]][["name"]],target_data[["data"]][["target"]][["gene_info"]][["geneid"]],target_data[["data"]][["target"]][["activity"]],target_data[["data"]][["disease"]][["name"]],target_data[["data"]][["drug"]][["molecule_name"]],target_data[["data"]][["drug"]][["molecule_type"]],sig_dbs[i],sig_paths[i])))
      ##colnames(drug_merged) <- c("Symbol","Name","Ensembl_ID","Modulation","Disorder","Molecule_Name","Molecule_Type")
      #write.table(drug_merged, file = outfile, row.names = FALSE, col.names=FALSE, sep = "\t", append = TRUE)
    }
    rm(target_data)
  }
}
colnames(merged_drugs) <- c("Target_ID","Target_Symbol","Target_Name","Associated_Disease_Count","Tractability_Count","sm_approved","sm_advancedClinical","sm_phase1","ab_approved","ab_advancedClinical","ab_phase1","pr_approved","pr_advancedClinical","pr_phase1","oc_approved","oc_advancedClinical","oc_phase1","Subcellular_Location","Safety_Liabilities","Number_Unique_Drugs","Drug_ID","Drug_Name","Is_FDA_Approved","Highest_Clinical_Trial_Phase","Has_Been_Withdrawn","Pathway_DB","Pathway_Name")
##colnames(merged_drugs) <- c("Target_ID","Target_Symbol","Target_Name","Drug_ID","Drug_Name","Is_FDA_Approved","Highest_Clinical_Trial_Phase","Has_Been_Withdrawn","Pathway_DB","Pathway_Name")
#merged_drugs <- unique(merged_drugs)
#write.table(merged_drugs, file = outfile, row.names = FALSE, col.names=TRUE, sep = "\t", append = FALSE)
print("Data gathering...complete")
print("Computing data...")


###########
#sort the existing table by the following order of criteria
# 1)  Pathway_Count,
# 2)  Tractability_Count,
# 2)  Number_Approved,
# 3)  Safety_Liabilities,
# 4)  Number_Unique_Drugs,
# 5)  Associated_Disease_Count,
# 6)  Number_phase3,
# 7)  Number_phase2,
# 8)  Number_phase1,
# 9)  Number_phase4

#Sorting step 1: iterate over whole table
#find counts for each target across all pathways
merged_drugs2 <- subset(merged_drugs, select = -c(Drug_ID,
                                                   Drug_Name,
                                                   Is_FDA_Approved,
                                                   Highest_Clinical_Trial_Phase,
                                                   Has_Been_Withdrawn
                                                   ))
merged_drugs2 <- unique(merged_drugs2)
merged_drugs2$Pathway_Name <- as.character(merged_drugs2$Pathway_Name)
merged_drugs2$Target_Symbol <- as.character(merged_drugs2$Target_Symbol)
target1 <- as.vector(merged_drugs2$Target_Symbol)
target1 <- unique(target1)
num_pathways <- as.vector(as.numeric(NULL))
for(a in 1:length(target1)){
  #a <- 3
  merged_drugs_temp <- as.data.frame(NULL)
  merged_drugs_temp <- subset(merged_drugs2, select = c(Pathway_Name,Target_Symbol))
  #merged_drugs_temp$Pathway_Name <- as.character(merged_drugs_temp$Pathway_Name)
  #merged_drugs_temp$Target_Symbol <- as.character(merged_drugs_temp$Target_Symbol)
  merged_drugs_temp <- subset(merged_drugs_temp, Target_Symbol == target1[a])
  num_pathways[a] <- nrow(merged_drugs_temp)
  #merged_drugs_temp <- subset(merged_drugs2, select = Pathway_Name & Target_Symbol %in% c(target1[a]))
}
rm(merged_drugs_temp)
rm(merged_drugs2)
num_path_df <- as.data.frame(cbind(num_pathways,target1))
num_path_df$num_pathways <- as.numeric(as.character(num_path_df$num_pathways))
num_path_df$target1 <- as.character(num_path_df$target1)
merged_drugs <- merge(merged_drugs,num_path_df, by.x='Target_Symbol', by.y='target1')

#Step2: iterate through each target
merged_drugs3 <- subset(merged_drugs, select = c(Target_Symbol,
                                                  Drug_Name,
                                                  Is_FDA_Approved,
                                                  Highest_Clinical_Trial_Phase,
                                                  Has_Been_Withdrawn
    ),
    stringsAsFactors = FALSE
  )
num4v <- as.vector(as.numeric(NULL))
num3v <- as.vector(as.numeric(NULL))
num2v <- as.vector(as.numeric(NULL))
num1v <- as.vector(as.numeric(NULL))
numApprovedv <- as.vector(as.numeric(NULL))

merged_drugs3 <- unique(merged_drugs3, stringsAsFactors = FALSE)
merged_drugs3$Target_Symbol<- as.character(merged_drugs3$Target_Symbol)
merged_drugs3$Target_Symbol<- as.character(merged_drugs3$Target_Symbol)
merged_drugs3$Is_FDA_Approved<- as.character(merged_drugs3$Is_FDA_Approved)
merged_drugs3$Highest_Clinical_Trial_Phase<- as.numeric(as.character(merged_drugs3$Highest_Clinical_Trial_Phase))

for(b in 1:length(target1)){
  #b <- 1
  phase_temp <- as.data.frame(subset(merged_drugs3, Target_Symbol == target1[b]), stringsAsFactors = FALSE)
  for(c in 1:nrow(phase_temp)){
    numApprovedv[b] <- as.numeric(sum(phase_temp$Is_FDA_Approved == "TRUE"))
    num3v[b] <- as.numeric(sum(phase_temp$Highest_Clinical_Trial_Phase == 3))
    num2v[b] <- as.numeric(sum(phase_temp$Highest_Clinical_Trial_Phase == 2))
    num1v[b] <- as.numeric(sum(phase_temp$Highest_Clinical_Trial_Phase == 1))
    num4v[b] <- as.numeric(sum(phase_temp$Highest_Clinical_Trial_Phase == 4))
  }
}
rm(merged_drugs3)
rm(phase_temp)
num_df <- as.data.frame(cbind(target1,numApprovedv, num3v, num2v, num1v, num4v))
merged_drugs <- merge(merged_drugs,num_df, by.x='Target_Symbol', by.y='target1')

colnames(merged_drugs) <- c("Target_Symbol","Target_ID","Target_Name","Associated_Disease_Count","Tractability_Count","sm_approved","sm_advancedClinical","sm_phase1","ab_approved","ab_advancedClinical","ab_phase1","pr_approved","pr_advancedClinical","pr_phase1","oc_approved","oc_advancedClinical","oc_phase1","Subcellular_Location","Safety_Liabilities","Number_Unique_Drugs","Drug_ID","Drug_Name","Is_FDA_Approved","Highest_Clinical_Trial_Phase","Has_Been_Withdrawn","Pathway_DB","Pathway_Name","Target_in_Pathways","num_Approved_Drugs","num_Phase3","num_Phase2","num_Phase1","num_Phase4")
merged_drugs$Tractability_Count <- as.numeric(as.character(merged_drugs$Tractability_Count))
merged_drugs$Safety_Liabilities <- as.numeric(as.character(merged_drugs$Safety_Liabilities))
merged_drugs$Number_Unique_Drugs <- as.numeric(as.character(merged_drugs$Number_Unique_Drugs))
merged_drugs$num_Approved_Drugs <- as.numeric(as.character(merged_drugs$num_Approved_Drugs))
merged_drugs$num_Phase3 <- as.numeric(as.character(merged_drugs$num_Phase3))
merged_drugs$num_Phase2 <- as.numeric(as.character(merged_drugs$num_Phase2))
merged_drugs$num_Phase1 <- as.numeric(as.character(merged_drugs$num_Phase1))
merged_drugs$num_Phase4 <- as.numeric(as.character(merged_drugs$num_Phase4))
merged_drugs$Associated_Disease_Count <- as.numeric(as.character(merged_drugs$Associated_Disease_Count))

#calculate the weighted score by multiplying metrics in each row by weighting factor (low, med, hi)
weighted_score_col <- as.vector(as.numeric(NULL))
for(j in 1:nrow(merged_drugs)){
  #j <- 1
  weighted_score <- as.numeric(0)
  weighted_score <- sum(weighted_score,(merged_drugs$Target_in_Pathways[j]*med))
  weighted_score <- sum(weighted_score,(merged_drugs$Tractability_Count[j]*med))
  weighted_score <- sum(weighted_score,(merged_drugs$num_Approved_Drugs[j]*med))
  weighted_score <- sum(weighted_score,(merged_drugs$Safety_Liabilities[j]*hi*-1))
  weighted_score <- sum(weighted_score,(merged_drugs$Number_Unique_Drugs[j]*med))
  weighted_score <- sum(weighted_score,(merged_drugs$Associated_Disease_Count[j]*med))
  weighted_score <- sum(weighted_score,(merged_drugs$num_Phase3[j]*p3_w*med))
  weighted_score <- sum(weighted_score,(merged_drugs$num_Phase2[j]*p2_w*med))
  weighted_score <- sum(weighted_score,(merged_drugs$num_Phase1[j]*p1_w*med))
  weighted_score <- sum(weighted_score,(merged_drugs$num_Phase4[j]*p4_w*med))
  weighted_score_col[j] <- weighted_score
}
merged_drugs$Weighted_Score <- weighted_score_col
colnames(merged_drugs) <- c("Target_Symbol","Target_ID","Target_Name","Associated_Disease_Count","Tractability_Count","sm_approved","sm_advancedClinical","sm_phase1","ab_approved","ab_advancedClinical","ab_phase1","pr_approved","pr_advancedClinical","pr_phase1","oc_approved","oc_advancedClinical","oc_phase1","Subcellular_Location","Safety_Liabilities","Number_Unique_Drugs","Drug_ID","Drug_Name","Is_FDA_Approved","Highest_Clinical_Trial_Phase","Has_Been_Withdrawn","Pathway_DB","Pathway_Name","Target_in_Pathways","num_Approved_Drugs","num_Phase3","num_Phase2","num_Phase1","num_Phase4","Weighted_Score")

merged_drugs <- merged_drugs[order(-merged_drugs$Weighted_Score,
                                    -merged_drugs$Target_in_Pathways,
                                   -merged_drugs$Tractability_Count,
                                   -merged_drugs$num_Approved_Drugs,
                                   merged_drugs$Safety_Liabilities,
                                   -merged_drugs$Number_Unique_Drugs,
                                   -merged_drugs$Associated_Disease_Count,
                                   -merged_drugs$num_Phase3,
                                   -merged_drugs$num_Phase2,
                                   -merged_drugs$num_Phase1,
                                   -merged_drugs$num_Phase4
),]
write.table(merged_drugs, file = outfile, row.names = FALSE, col.names=TRUE, sep = "\t", append = FALSE)

merged_drugs1 <- as.data.frame(merged_drugs, stringsAsFactors = FALSE)
merged_drugs1$Drug_ID <- NULL
merged_drugs1$Is_FDA_Approved <- NULL
merged_drugs1$Highest_Clinical_Trial_Phase <- NULL
merged_drugs1$Has_Been_Withdrawn <- NULL
merged_drugs1$Pathway_DB <- NULL
merged_drugs1$Pathway_Name <- NULL
#merged_drugs1 <- subset(merged_drugs1, select = -c("Drug_ID",
#                                                      "Drug_Name",
#                                                      "Is_FDA_Approved",
#                                                      "Highest_Clinical_Trial_Phase",
#                                                      "Has_Been_Withdrawn",
#                                                      "Pathway_DB",
#                                                      "Pathway_Name"),
#                                      stringsAsFactors = FALSE
#                               )
merged_drugs1$Drug_Name<- NULL
merged_drugs1$Tractability_Count <- as.numeric(as.character(merged_drugs1$Tractability_Count))
merged_drugs1$Safety_Liabilities <- as.numeric(as.character(merged_drugs1$Safety_Liabilities))
merged_drugs1$Number_Unique_Drugs <- as.numeric(as.character(merged_drugs1$Number_Unique_Drugs))
merged_drugs1$num_Approved_Drugs <- as.numeric(as.character(merged_drugs1$num_Approved_Drugs))
merged_drugs1$num_Phase3 <- as.numeric(as.character(merged_drugs1$num_Phase3))
merged_drugs1$num_Phase2 <- as.numeric(as.character(merged_drugs1$num_Phase2))
merged_drugs1$num_Phase1 <- as.numeric(as.character(merged_drugs1$num_Phase1))
merged_drugs1$num_Phase4 <- as.numeric(as.character(merged_drugs1$num_Phase4))
merged_drugs1$Associated_Disease_Count <- as.numeric(as.character(merged_drugs1$Associated_Disease_Count))
merged_drugs1$Weighted_Score <- as.numeric(as.character(merged_drugs1$Weighted_Score))

merged_drugs1 <- unique(merged_drugs1)
merged_drugs1 <- merged_drugs1[order(-merged_drugs1$Weighted_Score,
                                     -merged_drugs1$Target_in_Pathways,
                                     -merged_drugs1$Tractability_Count,
                                     -merged_drugs1$num_Approved_Drugs,
                                     merged_drugs1$Safety_Liabilities,
                                     -merged_drugs1$Number_Unique_Drugs,
                                     -merged_drugs1$Associated_Disease_Count,
                                     -merged_drugs1$num_Phase3,
                                     -merged_drugs1$num_Phase2,
                                     -merged_drugs1$num_Phase1,
                                     -merged_drugs1$num_Phase4
                                     ),]
write.table(merged_drugs1, file = outfile1, row.names = FALSE, col.names=TRUE, sep = "\t", append = FALSE)

if(images){
  #retrieve images for 10 most frequent Reactome pathways
  reactome_merged_drugs <- subset(merged_drugs,Pathway_DB=="Reactome")
  reactome_all_paths <- as.vector(reactome_merged_drugs$Pathway_Name)
  temp_path_counts <- as.data.frame(table(reactome_all_paths))
  temp_path_counts <- temp_path_counts[order(-temp_path_counts$Freq),]
  unique_reactome_paths <- as.vector(unique(reactome_all_paths))
  
  if(length(unique_reactome_paths) >= 10){
    unique_reactome_paths <- head(as.vector(temp_path_counts$reactome_all_paths),10)
  }else{
    unique_reactome_paths <- as.vector(temp_path_counts$reactome_all_paths)
  }

  #iterate through all unique pathways
  for(c in 1:length(unique_reactome_paths)){
    #c <- 1
    # Set base URL of API endpoint
    search_base_url <- "https://reactome.org/ContentService/search/query?query="
    search_mid_url <- curlEscape(unique_reactome_paths[c])
    search_end_url <- "&species=Homo%20sapiens&types=pathway&cluster=true&parserType=STD&Start%20row=0&rows=10&Force%20filters=false"
    url_var <- paste0(search_base_url,search_mid_url,search_end_url)
    getInfoInJson <- GET(url_var)
      #GET('https://reactome.org/ContentService/search/query?query=Major%20pathway%20of%20rRNA%20processing%20in%20the%20nucleolus%20and%20cytosol&species=Homo%20sapiens&types=pathway&cluster=true&parserType=STD&Start%20row=0&rows=10&Force%20filters=false')#, 
    #parse response
    res <- fromJSON(rawToChar(getInfoInJson$content))
    if(length(res[["results"]][["entries"]][[1]][["stId"]][1])==1){
      reactome_pathId <- res[["results"]][["entries"]][[1]][["stId"]][1]
      print(paste0("Pathway ID found: ",reactome_pathId))
    }else{
      print("Pathway ID doesn't exist")
    }
    print("Retrieving pathway image...")
    image_var <- paste0("https://reactome.org/ContentService/exporter/diagram/",reactome_pathId,".png")
    file_dest <- getwd()
    setwd("~/Downloads/")
    system(paste0("wget ",image_var," -p -k --random-wait"))
  }
}

print("Computing data...complete")
